version: '2.2'
services:
  spring-docker-demo-app:
    build:
      context: .
    depends_on:
      - mysqldb
    ports:
     - '8080:8080'
    networks:
     - springdockermysql-net
    environment:
     - spring.datasource.url=jdbc:mysql://mysqldb:3306/schooldb?allowPublicKeyRetrieval=true
  mysqldb:
    image: "mysql:8.0"
    restart: always
    environment:
      - MYSQL_DATABASE=schooldb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=schooluser
      - MYSQL_PASSWORD=password
    networks:
     - springdockermysql-net
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
networks:
  springdockermysql-net:
  